apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: staging
  namespace: flux-system
spec:
  interval: 0m30s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./deploy/staging
  prune: true