---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: staging
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: master
  url: https://github.com/herberthmas/flux-staging
  secretRef: flux-bootstrap-genkey

---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: staging
  namespace: flux-system
spec:
  interval: 2m0s
  path: ./
  prune: true
  sourceRef:
    kind: GitRepository
    name: staging

